processors:
  twitter: &twitter_processor
    processor: twitter
    args:
      queueSize: 100000
      consumerKey: $TWITTER_CONSUMER_KEY
      consumerSecret: $TWITTER_CONSUMER_SECRET
      accessToken: $TWITTER_ACCESS_TOKEN
      accessTokenSecret: $TWITTER_ACCESS_TOKEN_SECRET
      maxTweetNum: 200
      screenName: artsjpn

  delay: &delay_processor
    processor: delay
    args:
      queueSize: 100000
      intervalMilliSec: 5000
      group: [group]

  downloader: &downloader
    processor: downloader
    args:
      root_dir: ~/kniv
      paths: [group, user]

  custom: &custom_processor
    processor: custom
    args:
      logics:
        - type: filter_event_by_js
          commands: ['p.downloaded']
        - type: distinct
          keys: [since_id]
        - type: select_payload
          keys: [since_id, count, user, group]

pipelines:
  - name: twitter-download
    jobs:
      - <<: *twitter_processor
        consume: [init]
        produce: [twitter, download]
  # pipeline name
  - name: download
    jobs:
      - *delay_processor
      - *downloader
      - *custom_processor
      - *delay_processor
