processors:
  - processor: delay
    args:
      interval_millisec: 5000
      group: [group]
  - processor: download_from_url
    args:
      root_dir: ~/kniv
      paths: [group, user]
  - name: download_filter
    processor: custom
    args:
      logics:
        - type: filter_event_by_js
          commands: ['p.downloaded']
        - type: distinct
          keys: [since_id]
        - type: select_payload
          keys: [since_id, count, user, group]
pipelines:
  - name: twitter-download
    jobs:
      - processor: twitter
        consume: [init]
        produce: [twitter-download, download]
  - name: download
    jobs:
      - processor: delay
      - processor: download_from_url
      - processor: download_filter
      - processor: delay
